#!/bin/sh
# 2011-10-11 18:05:45
# alter mms

mpath=/usr/local/share/mradio
mms=/usr/local/share/mradio/mms
awk '{ print $1 ":" $2 }' $mms

#read input num and mms
reput()
{
    echo -e "Choose the radio you want to change("q" to quit):\c"
    read num
    case $num in
        q) break ;;
        [0-9]*) ;;
        *) break ;;
    esac
    max=$(tail -1 $mms | awk '{ print $1 }')
    if [ $num -gt $max ]
    then
        break
    fi
    echo -e "Please input mms:\c"
    read almms
    if [ -z "$almms" ]
    then
        echo -e "Invalid input please retry("q" to quit):\c"
        read numg
        case $numg in
            q) break ;;
            *) continue ;;
        esac
    fi
}

#alter mms file
alter()
{
    let "unum=$num-1"
    mnum=$(wc -l $mms | awk '{ print $1 }')
    let "dnum=$mnum-$num"
    head -$unum $mms > $mpath/umms
    tail -$dnum $mms > $mpath/dmms
    radio=$(awk -v arg="$num" '$1 ~ arg{ print $2 }' $mms)
    cat $mpath/umms > $mpath/mms
    echo -e "$num\t$radio\t$almms" >> $mpath/mms
    cat $mpath/dmms >> $mpath/mms
    rm $mpath/{umms,dmms} -f
    echo "Success!"
}

#recycle to alter mms
while [ 1 -eq 1 ]
do
    reput
    alter
done

echo "Goodbye!"
