#!/bin/sh
# 2011-09-01 18:56:27
# install

mpath=/usr/local/share/mradio
if [ ! -e $mpath ]  #$mpath no exsit create
then
    install -m 755 -d $mpath -v
fi
install -m 755 {addmms,play,altermms,mms} $mpath -v
install -m 755 mradio /usr/local/bin -v
