#!/bin/sh
# 2011-09-01 18:44:47
# mradio

mpath=/usr/local/share/mradio
if [ $# -eq 0 ] ; then
    $mpath/play
elif [ $# -eq 1 ] ; then
    case $1 in
        -a) $mpath/addmms ;;
        -c) $mpath/altermms ;;
        *) echo "Invalid!" ;;
    esac
fi
